# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [4]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
#Se debe determinar si algún elemento del array es igual a cero
igual_cero = np.any(a == 0)
if igual_cero == True:
    igual_cero = "Sí"
else:    igual_cero = "No"

print(f"Existe algún elemento igual a cero: {igual_cero}")

Existe algún elemento igual a cero: No


In [5]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
#Se debe determinar si existe algún elemento del array que sea distinto de cero
distinto_cero = np.any(a != 0)
if distinto_cero == True:
    distinto_cero = "Sí"
else:    distinto_cero = "No"
print(f"Existe algún elemento distinto de cero: {distinto_cero}")

Existe algún elemento distinto de cero: Sí


In [6]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
#Revisar si en el array existe algún elemento que sea NaN o infinito
nan_infinito = np.any(np.isnan(a)) or np.any(np.isinf(a))
if nan_infinito == True:
    nan_infinito = "Sí"
else:    nan_infinito = "No"
print(f"Existe algún elemento que sea NaN o infinito: {nan_infinito}")

Existe algún elemento que sea NaN o infinito: Sí


In [7]:
# ejercicio 4
a = np.array([1, 2, 3, np.inf])
# Revisar si en el array existe algún elemento que sea infinito
infinito = np.any(np.isinf(a))
if infinito == True:
    infinito = "Sí"
else:
    infinito = "No"
print(f"Existe algún elemento que sea infinito: {infinito}")

Existe algún elemento que sea infinito: Sí


In [8]:
# ejercicio 5
a = np.array([1, np.nan, 3])
# Revisar si en el array existe algún elemento que sea NaN
nan = np.any(np.isnan(a))
if nan == True:
    nan = "Sí"
else:    nan = "No"
print(f"Existe algún elemento que sea NaN: {nan}")

Existe algún elemento que sea NaN: Sí


In [11]:
# ejercicio 6
a= np.array([1, 3, 5])
b = np.array([2, 3, 4])
#Realizar una comparación elemento a elemento entre los arrays a y b, y determinar si son iguales, mayor que o menor que, colocar los números que se están comparando en el output
comparacion = np.where(a == b, "Iguales", np.where(a > b, "Mayor que", "Menor que"))
for i in range(len(a)):
    print(f"Comparación entre {a[i]} y {b[i]}: a es {comparacion[i]} que b")

Comparación entre 1 y 2: a es Menor que que b
Comparación entre 3 y 3: a es Iguales que b
Comparación entre 5 y 4: a es Mayor que que b


In [12]:
# ejercicio 7
#Crea un arreglo que contenga los valores: 1, 7, 13 y 10, determina el espacio en memoria que ocupa el arreglo
arreglo = np.array([1, 7, 13, 10])
espacio_memoria = arreglo.nbytes
print(f"El espacio en memoria que ocupa el arreglo es: {espacio_memoria} bytes")

El espacio en memoria que ocupa el arreglo es: 32 bytes


In [13]:
# ejercicio 8
#crea un arreglo de 10 ceros, uno de 10 unos y otro de 10 cincos
arreglo_ceros = np.zeros(10)
arreglo_unos = np.ones(10)
arreglo_cincos = np.full(10, 5)
print("Arreglo de 10 ceros:", arreglo_ceros)
print("Arreglo de 10 unos:", arreglo_unos)
print("Arreglo de 10 cincos:", arreglo_cincos)

Arreglo de 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Arreglo de 10 unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Arreglo de 10 cincos: [5 5 5 5 5 5 5 5 5 5]


In [14]:
# ejercicio 9
# crea un arreglo con todos los números enteros del 30 al 70
arreglo_enteros = np.arange(30, 71)
print(f"El arreglo con todos los números enteros del 30 al 70 es: {arreglo_enteros}")

El arreglo con todos los números enteros del 30 al 70 es: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
# ejercicio 10
# Crear un arreglo de los número pares del 30 al 70
arreglo_pares = np.arange(30, 71, 2)
print(f"El arreglo con todos los números pares del 30 al 70 es: {arreglo_pares}")

El arreglo con todos los números pares del 30 al 70 es: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [16]:
# ejercicio 11
# Crear una matriz de identidad 3x3
matriz_identidad = np.eye(3)
print(f"La matriz de identidad 3x3 es:\n{matriz_identidad}")

La matriz de identidad 3x3 es:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# ejercicio 12
# Generar un número aleatorio entre 0 y 1
numero_aleatorio = np.random.rand()
print(f"El número aleatorio generado entre 0 y 1 es: {numero_aleatorio}")

El número aleatorio generado entre 0 y 1 es: 0.8738898757650817


In [20]:
# ejercicio 13
#Crear un arreglo de 15 números aleatorios de una distribución normal estándar
arreglo_normal = np.random.randn(15)
print(f"El arreglo de 15 números aleatorios de una distribución normal estándar es:\n{arreglo_normal}")

El arreglo de 15 números aleatorios de una distribución normal estándar es:
[-2.16828218  2.11007895 -0.65862229  0.20326581  0.52930892 -1.64423305
 -0.55387441  1.20658285 -0.71236482  0.58333317 -0.99691096 -1.09023026
  1.04340582  1.07930645  1.59434363]


In [22]:
# ejercicio 14
#Crear un arreglo con valores entre 15 y 55 e imprime los valores menos el primero y el último
arreglo_valores = np.arange(15, 56)
print(f"El arreglo con valores entre 15 y 55 es:\n{arreglo_valores}")
print(f"\nEl arreglo sin el primer y último valor es:\n{arreglo_valores[1:-1]}")

El arreglo con valores entre 15 y 55 es:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

El arreglo sin el primer y último valor es:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [25]:
# ejercicio 15
# Crear un vector de longitud 10 con valores equitativamente entre 5 y 50
vector_equitativo = np.linspace(5, 50, 10)
print(f"El vector es:\n{vector_equitativo}")

El vector es:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# ejercicio 16
# Crea un vector con valores del 0 al 20 y cambia de signo del 9 al 15
vector = np.arange(0, 21)
vector[9:16] = -vector[9:16]
print(f"El vector es: \n{vector}")

El vector es: 
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [27]:
# ejercicio 17
# Convierte el arreglo a = np.array([1, 2, 3, 4, 5]) a una lista de python
a = np.array([1, 2, 3, 4, 5])
lista_python = a.tolist()
print(f"La lista ahora es: {lista_python}")

La lista ahora es: [1, 2, 3, 4, 5]


In [29]:
#ejercicio 18
# Dada la matriz a = np.array([[1, 2], [3, 4]]), verifica que números son pares y almacenalas en otra matriz
a = np.array([[1, 2], [3, 4]])
pares = a[a % 2 == 0]
print(f"Matriz con los números pares:\n{pares}")

Matriz con los números pares:
[2 4]


In [31]:
# ejercicio 19
#Convierte la lista l = [1, 2, 3] a un arreglo de numpy
l = [1, 2, 3]
print(f"La lista original es: {l}")
arreglo_numpy = np.array(l)
print(f"El arreglo de numpy es: {arreglo_numpy}")


La lista original es: [1, 2, 3]
El arreglo de numpy es: [1 2 3]


In [34]:
# ejercicio 20
#Dado el arreglo m = np.array([[1, 2, 3], [4, 5, 6]]), Encuentra el número de filas y columnas de la matriz
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape
print(f"El número de filas es: {filas}")
print(f"El número de columnas es: {columnas}")

El número de filas es: 2
El número de columnas es: 3
